version: '3.7'
name: cityguide-scout

networks:
  scout:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgis/postgis:17-3.4
    ports:
      - '5432:5432'
    networks:
      - scout
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
